eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}

test:
  cloud:
    conf: testSuccessCompleted

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream,beans,health,routes,httptrace,bus-refresh

spring:
  cloud:
    bus:
      enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

