eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/

test:
  cloud:
    conf: testSuccessCompleted

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream,beans,health,routes,httptrace,bus-refresh

spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest



